---
# This tells Flux where to find your Git repo
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dots
  namespace: flux-system
spec:
  interval: 5m # how often to check for new commits
  url: https://github.com/vypxl/dotfiles
  ref:
    branch: main
  secretRef:
    name: flux-system # credential created during bootstrap

---
# This tells Flux to apply everything in cluster/infra/
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: dots
  path: ./hosts/armada/cluster/infra
  prune: true # delete resources removed from git
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      DOMAIN: "lab.vypxl.io"

---
# This tells Flux to apply everything in cluster/apps/
# It depends on infra being ready first
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: dots
  path: ./hosts/armada/cluster/apps
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      DOMAIN: "lab.vypxl.io"
      LDAP_BASE_DN: "dc=lab,dc=vypxl,dc=io"
      ACME_EMAIL: "webmaster@vypxl.io"
