{ ... }:
{
  imports = [
    ./modules/bat.nix
    ./modules/direnv.nix
    ./modules/dotfiles.nix
    ./modules/dunst.nix
    ./modules/fish.nix
    ./modules/fuzzel.nix
    ./modules/git.nix
    ./modules/gnome-keyring.nix
    ./modules/helix.nix
    ./modules/hyprland.nix
    ./modules/kitty.nix
    ./modules/lazygit.nix
    ./modules/nvim.nix
    ./modules/python.nix
    ./modules/pylint.nix
    ./modules/scripts.nix
    ./modules/shell-utils.nix
    ./modules/ssh.nix
    ./modules/syncthing.nix
    ./modules/vim.nix
    ./modules/waybar.nix
    ./modules/wlogout.nix
    ./modules/xkb.nix
    ./modules/yamllint.nix
    ./modules/zed.nix
    ./modules/zellij.nix
  ];
}
