#! /usr/bin/env bash

logfile=/tmp/bootstrap.log

echo -e "\n\n------\nBootstrap start" >> $logfile
date >> $logfile
echo "------" >> $logfile
# Update
echo "Started bootstrap, log in /tmp/bootstrap.log"
echo "Updating pacman-mirrors"
sudo pacman-mirrors >> $logfile
echo "Upgrading current system"
sudo pacman -Syu --noconfirm >> $logfile

# Install paru and ruby
if ! command -v paru &> /dev/null; then
  echo "Installing paru..."
  sudo pacman -S --needed --noconfirm base-devel >> $logfile 2>&1
  git clone https://aur.archlinux.org/paru-bin.git >> $logfile 2>&1
  cd paru-bin
  makepkg -si --noconfirm >> $logfile 2>&1
  cd ..
  paru -S --noconfirm paru-bin >> $logfile 2>&1
  rm -rf paru-bin
fi

if ! command -v ruby &> /dev/null; then
  echo "Installing ruby..."
  sudo pacman -S --noconfirm ruby >> $logfile 2>&1
fi

echo "Bootstrapping system..."
cd ~/.bootstrap
ruby bootstrap.rb

