#! /bin/bash
IMG_URL=https://images.wallpapersden.com/image/download/cool-landscape-night-minimal-art_bGxna2aUmZqaraWkpJRobWllrWdma2U.jpg

# download image if not present
if [[ ! -f "~/.config/misc/image.png" ]]; then
  wget "$IMG_URL" -O /tmp/background_img 
  convert /tmp/background_img ~/.config/misc/image.png
  rm /tmp/background_img
fi

# install vim plugins
mkdir -p ~/.config/nvim/vundle
mkdir -p ~/.config/nvim/backup
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/vundle/Vundle.vim
nvim +PluginInstall +q +q

# install omf
curl -L https://get.oh-my.fish | fish
omf i bobthefish

