apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth/
  - bifrost.yaml
  - firecrawl.yaml
  - hindsight.yaml
  - openwebui.yaml
  - minecraft.yaml
  - postgres.yaml
  - headscale.yaml
  - homepage.yaml
  - secrets.yaml
  - whoami.yaml
