apiVersion: ENC[AES256_GCM,data:8FU=,iv:W2mBhGpqKNMdkIRQk3Jwihxe5YKQPQmMELG2zdoWOio=,tag:ocYJihZVaNZaUGKawIz4IQ==,type:str]
kind: ENC[AES256_GCM,data:kn1iyyvA,iv:CXHWdrcQdJoUH++jZOiH/UxxJ5yYwV7mELSo3cyNfWU=,tag:QMKfb8Fp+/WILq4okMqHnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p7YEKrp1eWj4,iv:ixZLrAdxQNgVgcU64rrAsuj93uaBGhoD6WIun44jW1g=,tag:bRRv0n4Ky6H8aKP0jLcZug==,type:str]
    namespace: ENC[AES256_GCM,data:BZpMiV/wgQ==,iv:SoX7G69PyHjtLHgKdzfYEtwau7+zlmNZgaRWHW/MZaY=,tag:79qBLFZRS5phTjE28x/F1Q==,type:str]
type: ENC[AES256_GCM,data:zP+ty50w,iv:qGjZ7OtFUo9juPIEA1N9pob4jVw7tR35VkMeFC5xZI4=,tag:OyCvz6wedQzCBvRq4Od8RQ==,type:str]
stringData:
    HEADSCALE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:luofRVPpV4LJyafueXUDGNeOysundL7vsbIVwzzT2ww=,iv:Sk92Z8z2oNEOzHJ79U8MspPBtG/REdZ2uyPVYVr2okI=,tag:w/+XkTpyvns5IzEfrxYv/Q==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cGp0MVozb3MzczhkcHZ0
            OWdPTC9HSzRnQWRDMllYVGZhL3NBVmVqcjNzClUzSnRTV3YzS3kxYkJXY2R6RkV4
            VjlaMWxlV2ZZRG9uYTY0WTBsdkJzYmsKLS0tIGpXMEIwdFE2WXJBMW1JODRYdU9w
            MDdXVzdMeDkwZXhYTEtMM1dIbm5PdzgKZBgyUkSWTzcc4PYF17F1ihgLZo1MyNIr
            N6u7CZljAeYO0vZJlkk4l4gT5PqY4Yr2qc7BnCOmabnQUmDI4ICPbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaSs2dXhicnpOZDNZWTds
            YmxiZmlIdnZ6SWVUYXg2a1JzR2RUZU9ZV3dJCjRTejNjYnpqZysvSVk1MmRKNnFz
            aldnT3FMMXU0SndEeDJyKzdGaFF5WXcKLS0tIDdjRy9kbFVBRHFqMGhFT3N3M1pE
            NGRkWnFrSjAzb0tZRk0vSEJieHlxTEEKT0+HDdvM/Qiwl3w6uj9/qtT7tOn8JBqp
            XedG56sDmzpiNc35MCqTX8OSIZk0g1FTjWs+VTE2SHklJOkFh+hojw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z2p4UFpSblhnTUw3c3lh
            bS8xVHRiem1LcUJEelpXUEZuSE0yUnMyUUFFCm5PMDlmSGtDNTVDYjlsUnJMR0U5
            YjRqVGdqTENoQThEQURGaVEyMzhWVmsKLS0tIHpIUXpXVjFkMy9OMVpOejRhYWYv
            eE9YZ0JxODBUNldZc2xCcllqaWltKzAKcY66hctNOIinx1MnCATfqxJzhckvXnxT
            JLWM1Tj6rWYBYoB6oiH0exjbm3rHDIQ8d8TLnJwFU8Kw2I+aVBghZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:48:55Z"
    mac: ENC[AES256_GCM,data:I5W7tYEDciVg39Tyj3068KARlkh2zZbfyw6eHEsHj9ppGIHRprnHfUXs6+fzxIwSgQnciEaPWDV4g+SxvPBcbfa9BcszSrniqeQ+pG86VKRhyd4QwQgLGf8TA4p4y2Hz+jANtPcB7nD6dK9aNog/Oy8KJxBC81AwbFL2b8GAL1o=,iv:QjnYOfV1gkZjBxabULy5Cms/dBiNTL/VrYWvPrajNLM=,tag:T9ipRFU5WOxFKwoWzoLNVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:8FU=,iv:W2mBhGpqKNMdkIRQk3Jwihxe5YKQPQmMELG2zdoWOio=,tag:ocYJihZVaNZaUGKawIz4IQ==,type:str]
kind: ENC[AES256_GCM,data:kn1iyyvA,iv:CXHWdrcQdJoUH++jZOiH/UxxJ5yYwV7mELSo3cyNfWU=,tag:QMKfb8Fp+/WILq4okMqHnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VhLiEsRLiQESXfK3,iv:DXl6XyL74phhygkTK9CN7XpKudMbCq+d7eF/xSm/oF0=,tag:eR0jswhMbdB0+7r3CzQG4w==,type:str]
    namespace: ENC[AES256_GCM,data:BZpMiV/wgQ==,iv:SoX7G69PyHjtLHgKdzfYEtwau7+zlmNZgaRWHW/MZaY=,tag:79qBLFZRS5phTjE28x/F1Q==,type:str]
type: ENC[AES256_GCM,data:zP+ty50w,iv:qGjZ7OtFUo9juPIEA1N9pob4jVw7tR35VkMeFC5xZI4=,tag:OyCvz6wedQzCBvRq4Od8RQ==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:lpf+B/PIs/wZN7ch16BdnKoqj2CjLDesQSJT0nE9CjkGvg9U0prigs/JrkGZJQL8DBYr1U0Q/DMITxuUKV0h5m6+pjKZbcFgyzbfuow93sLdMj1SxiIOXDM1PgvKIyDxm0KIKaBfFgXOIZcRVgHUem8j9V1xYtY6QPM+dEe1YCyXd/YPwMq3+IBDSUAUTOAmskOlp+Vt2Le1ZepkfR/DX/7Hpug=,iv:vnLX00E4sOorYb+Ket01bpFPczHC/LNqonfYjV6UyGA=,tag:fXpnlNDxdQ/1o2jMMurGAA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:xlQLF+TqH7KBLN8rrwyhsJTblEB2fdhoRFJAeqxjOM7sjByGwbF1i/GBgXsucL9rHdesyhcjCNuiOV3UOuDOm+ANBQin4sSJ9/RsnZeF+eU3FH8uEtymeWZfKSL23zdLmdSFh8pb0aXKrDMn,iv:KnuiAObDvxauNvmcxxM4at1ssD9JnoYriWb+p17Fl8U=,tag:3MPYiAhlBwDlbVorSw49xA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:rTA9xWJiSG7mPUWMsINV8z4nNRSmCHDEyHztyQUET2wc4tHtfUSD,iv:AfRDrKbyokVP5GTtPASoLdAzfSRqwtn9fZ2N9h3ETBo=,tag:feZ5nqbAcN6vSmzzdo4POw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:43BMV0YDqyW2byJGq/TawherbdWNLJLpTaRfYsFYydoz/0gwq/K/vH+P80sBpCQq/0hBnQHJ13IEhuZY8rAf3WCAcA6iwur4lg==,iv:TEJ2vSFih3P2CMq6a775U/7QGt3/wHL6UYhz32rj7Qo=,tag:n1cZiDDcfpW1GR+1p+8UgQ==,type:str]
    MOONSHOTAI_API_KEY: ENC[AES256_GCM,data:x6u4UfTd9iwkD4f0bNEynTcn5aXzqdP1Blyu3SO/WvVbzbAWm2F9xg20TpkYoy0Cop3u,iv:u56N3K4nwGZHEbKD+SDRmFiyIgPQ82jmI6cO4WEt25g=,tag:qlBnvvmJ0gxEP3fEb08QUw==,type:str]
    GROQ_API_KEY: ENC[AES256_GCM,data:kU3vh6oeEFVsYwo+11w1gnsoae7ppvxHF1gOMaOw/6fOA7RxJAJV2Z5kWXXj1jGQUl3C0x9XXyg=,iv:kj3FNMKkccWo6K38oGAmp34Ud5anbkaPZ2sdcPHJQJc=,tag:b6g1ExJsQTvPXKavwLo1pg==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cGp0MVozb3MzczhkcHZ0
            OWdPTC9HSzRnQWRDMllYVGZhL3NBVmVqcjNzClUzSnRTV3YzS3kxYkJXY2R6RkV4
            VjlaMWxlV2ZZRG9uYTY0WTBsdkJzYmsKLS0tIGpXMEIwdFE2WXJBMW1JODRYdU9w
            MDdXVzdMeDkwZXhYTEtMM1dIbm5PdzgKZBgyUkSWTzcc4PYF17F1ihgLZo1MyNIr
            N6u7CZljAeYO0vZJlkk4l4gT5PqY4Yr2qc7BnCOmabnQUmDI4ICPbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaSs2dXhicnpOZDNZWTds
            YmxiZmlIdnZ6SWVUYXg2a1JzR2RUZU9ZV3dJCjRTejNjYnpqZysvSVk1MmRKNnFz
            aldnT3FMMXU0SndEeDJyKzdGaFF5WXcKLS0tIDdjRy9kbFVBRHFqMGhFT3N3M1pE
            NGRkWnFrSjAzb0tZRk0vSEJieHlxTEEKT0+HDdvM/Qiwl3w6uj9/qtT7tOn8JBqp
            XedG56sDmzpiNc35MCqTX8OSIZk0g1FTjWs+VTE2SHklJOkFh+hojw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z2p4UFpSblhnTUw3c3lh
            bS8xVHRiem1LcUJEelpXUEZuSE0yUnMyUUFFCm5PMDlmSGtDNTVDYjlsUnJMR0U5
            YjRqVGdqTENoQThEQURGaVEyMzhWVmsKLS0tIHpIUXpXVjFkMy9OMVpOejRhYWYv
            eE9YZ0JxODBUNldZc2xCcllqaWltKzAKcY66hctNOIinx1MnCATfqxJzhckvXnxT
            JLWM1Tj6rWYBYoB6oiH0exjbm3rHDIQ8d8TLnJwFU8Kw2I+aVBghZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:48:55Z"
    mac: ENC[AES256_GCM,data:I5W7tYEDciVg39Tyj3068KARlkh2zZbfyw6eHEsHj9ppGIHRprnHfUXs6+fzxIwSgQnciEaPWDV4g+SxvPBcbfa9BcszSrniqeQ+pG86VKRhyd4QwQgLGf8TA4p4y2Hz+jANtPcB7nD6dK9aNog/Oy8KJxBC81AwbFL2b8GAL1o=,iv:QjnYOfV1gkZjBxabULy5Cms/dBiNTL/VrYWvPrajNLM=,tag:T9ipRFU5WOxFKwoWzoLNVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
