apiVersion: ENC[AES256_GCM,data:8FU=,iv:W2mBhGpqKNMdkIRQk3Jwihxe5YKQPQmMELG2zdoWOio=,tag:ocYJihZVaNZaUGKawIz4IQ==,type:str]
kind: ENC[AES256_GCM,data:kn1iyyvA,iv:CXHWdrcQdJoUH++jZOiH/UxxJ5yYwV7mELSo3cyNfWU=,tag:QMKfb8Fp+/WILq4okMqHnA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dJ6sDP/CnSlggMn62XI=,iv:ULQY+ZlQ/DUm1tKcE5aAFOzfZDU/YATNsI3OhDtXcyI=,tag:/HxCBGKJ21toLkgWFIKb8g==,type:str]
    namespace: ENC[AES256_GCM,data:0nOHjbdeLBiK,iv:a49NbVOp5+ClOnR3TrxmUpvaIfVnZn+ORRgkXs50Ffg=,tag:pCKbNnpwZ8Wzd83hFHnB3w==,type:str]
type: ENC[AES256_GCM,data:zP+ty50w,iv:qGjZ7OtFUo9juPIEA1N9pob4jVw7tR35VkMeFC5xZI4=,tag:OyCvz6wedQzCBvRq4Od8RQ==,type:str]
stringData:
    HEADSCALE_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:luofRVPpV4LJyafueXUDGNeOysundL7vsbIVwzzT2ww=,iv:Sk92Z8z2oNEOzHJ79U8MspPBtG/REdZ2uyPVYVr2okI=,tag:w/+XkTpyvns5IzEfrxYv/Q==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cGp0MVozb3MzczhkcHZ0
            OWdPTC9HSzRnQWRDMllYVGZhL3NBVmVqcjNzClUzSnRTV3YzS3kxYkJXY2R6RkV4
            VjlaMWxlV2ZZRG9uYTY0WTBsdkJzYmsKLS0tIGpXMEIwdFE2WXJBMW1JODRYdU9w
            MDdXVzdMeDkwZXhYTEtMM1dIbm5PdzgKZBgyUkSWTzcc4PYF17F1ihgLZo1MyNIr
            N6u7CZljAeYO0vZJlkk4l4gT5PqY4Yr2qc7BnCOmabnQUmDI4ICPbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaSs2dXhicnpOZDNZWTds
            YmxiZmlIdnZ6SWVUYXg2a1JzR2RUZU9ZV3dJCjRTejNjYnpqZysvSVk1MmRKNnFz
            aldnT3FMMXU0SndEeDJyKzdGaFF5WXcKLS0tIDdjRy9kbFVBRHFqMGhFT3N3M1pE
            NGRkWnFrSjAzb0tZRk0vSEJieHlxTEEKT0+HDdvM/Qiwl3w6uj9/qtT7tOn8JBqp
            XedG56sDmzpiNc35MCqTX8OSIZk0g1FTjWs+VTE2SHklJOkFh+hojw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z2p4UFpSblhnTUw3c3lh
            bS8xVHRiem1LcUJEelpXUEZuSE0yUnMyUUFFCm5PMDlmSGtDNTVDYjlsUnJMR0U5
            YjRqVGdqTENoQThEQURGaVEyMzhWVmsKLS0tIHpIUXpXVjFkMy9OMVpOejRhYWYv
            eE9YZ0JxODBUNldZc2xCcllqaWltKzAKcY66hctNOIinx1MnCATfqxJzhckvXnxT
            JLWM1Tj6rWYBYoB6oiH0exjbm3rHDIQ8d8TLnJwFU8Kw2I+aVBghZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T15:04:01Z"
    mac: ENC[AES256_GCM,data:gIn4PiGuQA5fWAKqV6jFxW7CH6km7jl9Si2Mu392qwwDG7SN9TYkEJAaqIPEpv9hNv1LdlpQ1jzJ3k9hkRfPQMCDKRmcMCIUDLH4GcA4G/jRklK7idOpl+scePdJmYsulvhY+gO7elkose+8jXHu8yv+WOXXSZVsHh5nxqqvyBk=,iv:VKgcaObsLLnKq94udYJmO8v7Nrmua5tQuJj5xpb3eGk=,tag:lHKu29NR9Kx95fUSRBuNSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
