#! /bin/sh

echo "Starting bspwm config.."
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x compton > /dev/null || compton &
xrandr --output DP-2 --primary --auto --right-of HDMI-0

feh --bg-center ~/.config/misc/image.png &
~/.config/polybar/launch.sh &
setxkbmap us
setxkbmap -option compose:ralt

bspc monitor DP-2 -d I IV V VI VII VIII IX X
bspc monitor HDMI-0 -d II III

bspc config border_width         4
bspc config focused_border_color "#285577"
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config paddingless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus none
bspc config focus_follows_pointer on
# bspc config pointer_follows_focus on

gap=20
bspc config top_padding 50
bspc config bottom_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap

bspc rule -a Chromium desktop='^2'
bscp rule -a polybar manage=off

echo "before subscribe"

bspc subscribe node_focus | while read -a msg ; do
  desk_id=${msg[2]}
  wind_id=${msg[3]}
  if [ $(bspc query -d $desk_id -N | wc -l) -eq 1 ]; then
    bspc config -d "$desk_id" window_gap -20
  else
    bspc config -d "$desk_id" window_gap 20
  fi
done &

echo "End of bspwm config"
