#! /bin/bash
IMG_URL=https://wallpapershome.com/images/wallpapers/yosemite-5120x2880-5k-4k-wallpaper-8k-forest-osx-apple-mountains-3944.jpg 

# download image if not present
if [[ ! -f "~/.config/misc/image.png" ]]; then
  wget "$IMG_URL" -O /tmp/background_img 
  convert /tmp/background_img ~/.config/misc/image.png
  rm /tmp/background_img
fi

# install vim plugins
nvim +PluginInstall +q +q

# Code setup
# echo -e "\033[1;36mInstalling Code settings sync extension..\033[0m"
# code --install-extension Shan.code-settings-sync

# echo -e "\n\033[1;32mTo install VSCode Settings, install Shan.code-settings-sync extension,\nfork my https://gist.github.com/vypxl/f0648b4d9ab3b383b9874641b00efb97 gist\nand provide its id to the extension after creating a github token\033[0m"
