#! /usr/bin/env bash

BATINFO="$(acpi -b | grep -i discharging | awk '/Battery 0/{print $5;}')"
if [ -z "$BATINFO" ]; then
    exit
fi
if [[ "$BATINFO" < 00:10:00 ]]; then
    notify-send -a Battery -i Battery -u critical "Battery critical!" "Please plug in."
fi
