apiVersion: ENC[AES256_GCM,data:DoQ=,iv:6OHj24Vyumd271SWM3AhpI8xyle8/kAbm89s0u7Uxlc=,tag:uOpJuV6CdiGCo8DkbIIEqQ==,type:str]
kind: ENC[AES256_GCM,data:Nesm0pIr,iv:nOwam13M/SQcJT0g0ai5APrdV9fkMMu5fmqF3UIJb5g=,tag:/S8Sq/ZFt3Rvr6Nho9gwVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lhkIZBs=,iv:W+mH3PnCdMSkosSWZww25fvrwJsZz1ZyY0Xa0y6JE+c=,tag:hnG6ovE8Ugn445Ndsja2uw==,type:str]
    namespace: ENC[AES256_GCM,data:P50j9A==,iv:vDTFXKDRUHmQYWlTzTLPSCk0aM2y4p7p7vIlh/FHDQg=,tag:2EY1Excnu4x7N8HHzU2u5w==,type:str]
type: ENC[AES256_GCM,data:TUbgpb+Z,iv:FRgKBcbK09IQMeZr/Wru3pN5KmC4gvIP8IMXsm5gpRE=,tag:9qGgin0ejn7s9PgecsI3Eg==,type:str]
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:MJcyJQG/xiKUUMrIWPaXzpd5MThqz6gUUpKOgJySJJMk5ge+xF0IBfe2ILQ=,iv:fKxFQYOmTSk1h6t2ogIEvQXtGLSz7Gjtln9HLtr7yhc=,tag:b8FuK8hQLB7Jv7o78QxITA==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:yxvkHpuIXbEY4Yy2MdAwx4E+Qryzlv7HPfUy/M8bDeE=,iv:rjg8ERX0y5dVYU/Izc6Eb9rptr7b8ZiYK3SukVFe1e8=,tag:s572ChJ/oyph6xrrw8skjQ==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cVpweEllWUQ5OTQra0Qx
            am5XSmdqMnZnK0NSaUh2dDhLS1dJSHBSNlJ3CkdlcUdpKzVJYTgxanhoS0E2TWhI
            Q25FYTlacWlkQjhjTlQrS2Q3Y2lSSWsKLS0tIFBZcjZHalRDNllxWkhLVFo2S01I
            Qi9zOTVHbVlZTE1PVlhQSnU4VzR4SFUKbqkQkeJmd1UP0cNOvDJrig/IfuV31/m9
            AIE2znrvaJvv2/Ho4oCjYT8ruVv3jbpsY5SxdPAU6hv6OM5zjTJviw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RXkxU096R3BFakJhRlFR
            QUJoMkZDMW9EaldaQlpRMVArSUpRcVRoRG4wCmJkcThQY3hJYWVUNW9udU9BUUpH
            TjAzb1BLRDgyeEVxa3liUnVjejBNbkkKLS0tIGZEcDNsMURRT1IvQ1kvN0Fkc0Nk
            aTdjZXRYQlUwZlFJZitDTStHcW03ZzQKe0u7/HwP8s34YCKcWe2lvqaPdPdVRRCv
            Qy2I7CARLCMGI9iH1trqZDZwB/+319upFlqjEVNf7vV3A/WGsdiiXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR09NeUZpWXZjTEJSTUMz
            dW5iRVE3ajk3aVJhRnkvU0J0c3huOEFwVUZjClozWkVDaEUxeWsrTDEraE1YN0Q4
            STBiUitSUVAxSFNnOG5pWDhxQS9yNzQKLS0tIDA0MlkrUFBWcWd3MUlCOEkxdXZ4
            eWVGZUV1Q3dOYXh0WUpnRXc4YmdsZHcK597RD35vGr2XIzDSw6XaklpQTxETE/K9
            A8qaup651mmXqVy0M4PSaQjTzTSqmauZ1lfBRgJq6DXnZIQLmKEzqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T09:37:54Z"
    mac: ENC[AES256_GCM,data:DAh6eXSMyLv/l4Cq4exPE2+IVwYUkcsZDaTmStyimcdSdeUS7MT9BWULtjfb0kUurESeT3DsIp48aE4+RyY7YgLePG/P1eLYouHFzEtRnhgqAad6eLNVvyOrHOGBQBBi7CCmC7udAciaN7JP4J6ElwGRA5UoO/sGmzAYE5eC1r8=,iv:g+Ac2viKtiKGXdyEU6FrvdRbA1m9A/T8gvgrMO7IX2g=,tag:iKwzihOeIu1OTFkgehUjWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:DoQ=,iv:6OHj24Vyumd271SWM3AhpI8xyle8/kAbm89s0u7Uxlc=,tag:uOpJuV6CdiGCo8DkbIIEqQ==,type:str]
kind: ENC[AES256_GCM,data:Nesm0pIr,iv:nOwam13M/SQcJT0g0ai5APrdV9fkMMu5fmqF3UIJb5g=,tag:/S8Sq/ZFt3Rvr6Nho9gwVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vmmAI/nLNhw=,iv:G50TND3FH6y1jA7C2IDTv7BNAt4CIb8/LKSxd9fmSWY=,tag:35W6yODEtZTNiogKKfryfQ==,type:str]
    namespace: ENC[AES256_GCM,data:P50j9A==,iv:vDTFXKDRUHmQYWlTzTLPSCk0aM2y4p7p7vIlh/FHDQg=,tag:2EY1Excnu4x7N8HHzU2u5w==,type:str]
type: ENC[AES256_GCM,data:TUbgpb+Z,iv:FRgKBcbK09IQMeZr/Wru3pN5KmC4gvIP8IMXsm5gpRE=,tag:9qGgin0ejn7s9PgecsI3Eg==,type:str]
stringData:
    SECRET: ENC[AES256_GCM,data:6HnNRPG4xK6W+RRPAGH/9huYjNXuiqImfYXB8P9gSrabAOCTneJS1xfBpcY=,iv:Tk6xxj9xzBInhmi4eS14CG+Nd5q7q3+1aPKJEDG3uWY=,tag:hC4xPYr0rs4tea8386tu2g==,type:str]
    #ENC[AES256_GCM,data:plELl6wvItSJ/Y6ZylIT5xT8riPyA4epDoHmZdqgEjM4oh3XM1VADpOHLzyGD/3NsjXLmjS5RKkBgmQk7K7L2oTiw01yInNn/8w=,iv:2wWiQGGnO/Cj9l6rHgdThOxvTCLrXxmkQpL47e1yjcU=,tag:fRcFtjhpzB8j3xRMQHZPxw==,type:comment]
    #ENC[AES256_GCM,data:jgZJpWe/ryHvQzNiONRQGS6fUDL+7Hf4uoUqXwWOFiHjX7ZFcw+85rDY37X2C9gtU0An,iv:J6NIcioFiRuojXIr5A793WOkKWlVuriUBc2rBHyQ+D4=,tag:CxKzYZ5nz7Bc80qdAiuzFQ==,type:comment]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: ENC[AES256_GCM,data:njFNzIetE5U69P0oHtUQiLDWh1RjPTJKO+YrS1Oz5TiarwWc,iv:ag8CEnu6Q32R5rimXCbAPGsf5Ugnn+8BIa6EinVSGRs=,tag:Ut1dsDZ7IMS4cgvKFVRTxA==,type:str]
    TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: ENC[AES256_GCM,data:Xm3EVuhq9N/g40YcltebYOoZLbSL6cRfAH05usMAlGU=,iv:LF6n2xV0CSLxGEafreak6dJ7FXy6q2TbqF/6chN/6jQ=,tag:79KqvlJ9Iuva21Qj90LkPw==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cVpweEllWUQ5OTQra0Qx
            am5XSmdqMnZnK0NSaUh2dDhLS1dJSHBSNlJ3CkdlcUdpKzVJYTgxanhoS0E2TWhI
            Q25FYTlacWlkQjhjTlQrS2Q3Y2lSSWsKLS0tIFBZcjZHalRDNllxWkhLVFo2S01I
            Qi9zOTVHbVlZTE1PVlhQSnU4VzR4SFUKbqkQkeJmd1UP0cNOvDJrig/IfuV31/m9
            AIE2znrvaJvv2/Ho4oCjYT8ruVv3jbpsY5SxdPAU6hv6OM5zjTJviw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RXkxU096R3BFakJhRlFR
            QUJoMkZDMW9EaldaQlpRMVArSUpRcVRoRG4wCmJkcThQY3hJYWVUNW9udU9BUUpH
            TjAzb1BLRDgyeEVxa3liUnVjejBNbkkKLS0tIGZEcDNsMURRT1IvQ1kvN0Fkc0Nk
            aTdjZXRYQlUwZlFJZitDTStHcW03ZzQKe0u7/HwP8s34YCKcWe2lvqaPdPdVRRCv
            Qy2I7CARLCMGI9iH1trqZDZwB/+319upFlqjEVNf7vV3A/WGsdiiXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR09NeUZpWXZjTEJSTUMz
            dW5iRVE3ajk3aVJhRnkvU0J0c3huOEFwVUZjClozWkVDaEUxeWsrTDEraE1YN0Q4
            STBiUitSUVAxSFNnOG5pWDhxQS9yNzQKLS0tIDA0MlkrUFBWcWd3MUlCOEkxdXZ4
            eWVGZUV1Q3dOYXh0WUpnRXc4YmdsZHcK597RD35vGr2XIzDSw6XaklpQTxETE/K9
            A8qaup651mmXqVy0M4PSaQjTzTSqmauZ1lfBRgJq6DXnZIQLmKEzqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T09:37:54Z"
    mac: ENC[AES256_GCM,data:DAh6eXSMyLv/l4Cq4exPE2+IVwYUkcsZDaTmStyimcdSdeUS7MT9BWULtjfb0kUurESeT3DsIp48aE4+RyY7YgLePG/P1eLYouHFzEtRnhgqAad6eLNVvyOrHOGBQBBi7CCmC7udAciaN7JP4J6ElwGRA5UoO/sGmzAYE5eC1r8=,iv:g+Ac2viKtiKGXdyEU6FrvdRbA1m9A/T8gvgrMO7IX2g=,tag:iKwzihOeIu1OTFkgehUjWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:DoQ=,iv:6OHj24Vyumd271SWM3AhpI8xyle8/kAbm89s0u7Uxlc=,tag:uOpJuV6CdiGCo8DkbIIEqQ==,type:str]
kind: ENC[AES256_GCM,data:Nesm0pIr,iv:nOwam13M/SQcJT0g0ai5APrdV9fkMMu5fmqF3UIJb5g=,tag:/S8Sq/ZFt3Rvr6Nho9gwVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ayAAUWPv/Z3O,iv:wRftmBo865a0ndgBH/69NSy4Y4qkGFKJBpk9hY1gpG0=,tag:xME5ykmGN8ZBuoCV+htoag==,type:str]
    namespace: ENC[AES256_GCM,data:P50j9A==,iv:vDTFXKDRUHmQYWlTzTLPSCk0aM2y4p7p7vIlh/FHDQg=,tag:2EY1Excnu4x7N8HHzU2u5w==,type:str]
type: ENC[AES256_GCM,data:TUbgpb+Z,iv:FRgKBcbK09IQMeZr/Wru3pN5KmC4gvIP8IMXsm5gpRE=,tag:9qGgin0ejn7s9PgecsI3Eg==,type:str]
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:ux7QebxlTzAShRsTDTHosnOpL88jvYwvp9YeRxeV5ODUHyNQKC/n+8Xv8qQ=,iv:jeKOblhkBYJ0YmjdjrhKTBCMiyXbsu6SDgv5bz7+z30=,tag:PERQ/2mtZoU0RdFFCCEXAA==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cVpweEllWUQ5OTQra0Qx
            am5XSmdqMnZnK0NSaUh2dDhLS1dJSHBSNlJ3CkdlcUdpKzVJYTgxanhoS0E2TWhI
            Q25FYTlacWlkQjhjTlQrS2Q3Y2lSSWsKLS0tIFBZcjZHalRDNllxWkhLVFo2S01I
            Qi9zOTVHbVlZTE1PVlhQSnU4VzR4SFUKbqkQkeJmd1UP0cNOvDJrig/IfuV31/m9
            AIE2znrvaJvv2/Ho4oCjYT8ruVv3jbpsY5SxdPAU6hv6OM5zjTJviw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RXkxU096R3BFakJhRlFR
            QUJoMkZDMW9EaldaQlpRMVArSUpRcVRoRG4wCmJkcThQY3hJYWVUNW9udU9BUUpH
            TjAzb1BLRDgyeEVxa3liUnVjejBNbkkKLS0tIGZEcDNsMURRT1IvQ1kvN0Fkc0Nk
            aTdjZXRYQlUwZlFJZitDTStHcW03ZzQKe0u7/HwP8s34YCKcWe2lvqaPdPdVRRCv
            Qy2I7CARLCMGI9iH1trqZDZwB/+319upFlqjEVNf7vV3A/WGsdiiXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR09NeUZpWXZjTEJSTUMz
            dW5iRVE3ajk3aVJhRnkvU0J0c3huOEFwVUZjClozWkVDaEUxeWsrTDEraE1YN0Q4
            STBiUitSUVAxSFNnOG5pWDhxQS9yNzQKLS0tIDA0MlkrUFBWcWd3MUlCOEkxdXZ4
            eWVGZUV1Q3dOYXh0WUpnRXc4YmdsZHcK597RD35vGr2XIzDSw6XaklpQTxETE/K9
            A8qaup651mmXqVy0M4PSaQjTzTSqmauZ1lfBRgJq6DXnZIQLmKEzqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T09:37:54Z"
    mac: ENC[AES256_GCM,data:DAh6eXSMyLv/l4Cq4exPE2+IVwYUkcsZDaTmStyimcdSdeUS7MT9BWULtjfb0kUurESeT3DsIp48aE4+RyY7YgLePG/P1eLYouHFzEtRnhgqAad6eLNVvyOrHOGBQBBi7CCmC7udAciaN7JP4J6ElwGRA5UoO/sGmzAYE5eC1r8=,iv:g+Ac2viKtiKGXdyEU6FrvdRbA1m9A/T8gvgrMO7IX2g=,tag:iKwzihOeIu1OTFkgehUjWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
