apiVersion: ENC[AES256_GCM,data:5TI=,iv:tY/NaK7Vp7SDvqkOmvVc4INA/zrscxquCzIsJQpw21w=,tag:ZBPjNN928lnQ7Lhr9BQEkg==,type:str]
kind: ENC[AES256_GCM,data:cjU4NvoZ,iv:7p20s0f6u7XjQEJIY+ktZG5yZRPPzz2b+MfjjDnrm78=,tag:UEZEIBXFt3EnEdvxRnhtug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mKiahg==,iv:tOP/RZTQpr8xdN5qsP/K5RJYbNLwwrzgInZQ33wnpIY=,tag:5yjaGv47iUP/LKmE5YGu6Q==,type:str]
    namespace: ENC[AES256_GCM,data:cCR0wg==,iv:SaJj/0hAgbMg51Zcfg/N55SPIv8rE6mUW8TEL2nirKE=,tag:IpwfFeHZAUh+sgllYflVbg==,type:str]
type: ENC[AES256_GCM,data:sbVqXIq+,iv:evKQnpHNu7M7VnXwNw1RAhEhlhnt5GE3Ss55LBaZy2A=,tag:P4d4dzOD7oqiw4V6lqap/Q==,type:str]
stringData:
    BASIC_AUTH_USER: ENC[AES256_GCM,data:gH64kjA=,iv:zE9J9mJlHTTyp3NYpBUlJcqHBexk3eY3pOGqYh5B5B8=,tag:GjlI1/L6S8aygSbHfOPBQQ==,type:str]
    BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:pExswUw/DuRKAHpTvg44JWxFGndgCN7f/oYmPn0cCPOzsqz1CVoii1Y=,iv:+wN4UeUaf4r2OVBQhpJl1qxWmUSj75UxNGglXVEhSvI=,tag:Wi04Fkc9+Eu+kozpuNSEwQ==,type:str]
sops:
    age:
        - recipient: age1q6xyz7l5vcsetamg5ged24n03zfezlk3jh2pv2s0k95k593yzf6qqpw44j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydk5nbm5lNEpuN1czLzRW
            dVBzU3ZMMEtsMnJFWDR4ZFZxUWFxT0VtdURzCm1HL09vN2FZc0g0dGMyTkM2YzlL
            NXVpT2RyRG80L0hnbUprdDdSeVUvb3MKLS0tIFdSSms4YUxXTGNtZEZzOGJwVzVn
            c0gvR1BsMlFsZjFNamxLcDRnbXR5SEkKpgFn/Ny9DjjQVHqFKdk3wVj/zSnpW2qk
            0Fkm3g/dlFpV8RtaKOoEsPBX0sfwhBtTS1nWVXPJDTh/qNSG4/mQ4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age153l73h58e4uq0celj0x8w7r5972l6m2ewghkd9t2wgdzcdhkzcusmx83ej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MmxzeVdBN2ZFQlBJZDNu
            R2NaTU5rRjBpcVJocXlORXdZMXZTQ1BXMmhnCmZNUjdiRUJCRkR4LzRyRUJMMGQw
            dGtKQzhHZHJMdnYzUVg4VUpSam9Ga1UKLS0tIEV5andVa0ptZmhRamUrSWV4dno3
            RFBxVVRaZkpldENtUXY3UEhreG9wNHcKU8RvMOny/9nukCW+HudAe7v+K8zAeP16
            qw2oFcwOH9y23y30CzwuzXvWSQaCx/M2CiPpMUmM7O9/L2AgfyHvZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14nsx7zwx4ajadyly7amsdyarwfp04qgu7r6x70szzcr9t7hn85csha23fu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcW1Ib3czMUdBQVgyeDZE
            aUd3NmRHcVAvTXhVckxJQ205dXFoVmxVWEVjCjRldkd3alZyMXNqZDJpbEdxK3M3
            THhpaGFSeFJTWXpVSnplcmROblFlRmcKLS0tIERnLzZIdUVnVWNRbktBdm9oNHNy
            MTFxZUZTQ1V2ZktJYlY4N1JZTGxRUUEK6M2mJ2BZMklP9ntnJAPBXxzOFYU71GWg
            bmHhwNBwnXkzAL+w8JMWmQA1a4HpwNhL4tFCfXLONIo5poluhYG4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T12:51:29Z"
    mac: ENC[AES256_GCM,data:2oOgbkB5PZbxMz3mK8Dx6+ARhZuSzQAAL9YvmohPy3J5XhVm853Ogfbt7zSommgnlCtTk7oxGQxfe2jH7Mw5gF7TjxRK6hVruLzd4uS1VupYmFGWwhDco6esmyz249/Rvl68QEl+37FzZTr2U2aV+aLAJTLpmitQcmj0AtLjEEo=,iv:Iv3r3Kf/Mebatwv6fDf+WjO1QyNW8h6fGwSVl7ACqJA=,tag:mVpBHNtXGokog4MkeHSkbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
